### ISSUE TITLE
Background option works too well

### ISSUE THREAD

**Issue by mattdale77** [QubesOS/qubes-desktop-linux-menu#29]
Using --help it suggests that there is a --background option. Using this at launch backgrounds the menu so well that it does not even pop up when the toolbar button is pressed.

I would expect it to not pop up at initial launch but still appear when the toolbar launcher button is pressed

If it is relevant, this is in Qubes 4.1.2

**Comment by marmarta** [comment]
This should have been fixed by https://github.com/QubesOS/qubes-desktop-linux-menu/commit/87d8b50c15218401622eb8cf34a48278d80f51da ; if it persists on an updated system, please reopen.
