### ISSUE TITLE
GDbus error: The name is not activatable

### ISSUE THREAD

**Issue by princessalicorn** [QubesOS/qubes-desktop-linux-menu#7]
Qubes OS release:
R4.1

Brief summary:

After installing and adding the launcher to xfce as instructed in the github repo, the launcher does not open. 
I copied the command and ran it in my terminal (gdbus call --session --dest org.qubesos.appmenu --object-path "/org/qubesos/appmenu" --method org.freedesktop.Application.Activate "{}")

It responds with:

Error: GDbus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable

Steps to reproduce

 Install the Qube with "sudo qubes-dom0-update --enablerepo=qubes-dom0-unstable qubes-desktop-linux-menu"
 Add the .desktop file to the launcher
 Try to run the launcher (it does not open)
 
 or
 
 Run the command in the .desktop file in the terminal (gdbus call --session --dest org.qubesos.appmenu --object-path "/org/qubesos/appmenu" --method org.freedesktop.Application.Activate "{}")
 Receive error: 
 Error: GDbus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable

Expected behavior
The linux menu starts as expected

Actual behavior
The launcher does not start

**Comment by marmarta** [comment]
That should have been fixed in 4.2
